[build]
  publish = "."             # Publica los archivos desde la raíz de tu repo (donde está index.html)
  functions = "netlify/functions" # Indica dónde están tus Netlify Functions

# Redirecciones para tus API endpoints
# Esto mapea solicitudes a /api/nombre-funcion a la función real
# en Netlify que se ejecuta en /.netlify/functions/nombre-funcion
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200